kind: ConfigMap
apiVersion: v1
metadata:
  name: "$(getConfig \"LIB_APP_TEST_NAME\")"
  namespace: "$(getConfig \"LIB_APP_TEST_NAMESPACE\")"
  labels:
    app.kubernetes.io/name: "$(getConfig \"LIB_APP_TEST_NAME\")"
    app.kubernetes.io/managed-by: "$(getConfig \"LIB_APP_TEST_MANAGER\")"
    app.kubernetes.io/version: "$(getConfig \"lib.app.test.version\")"
    app.kubernetes.io/component: "$(getConfig \"LIB_APP_TEST_NAME\")"
    app.kubernetes.io/part-of: "$(getConfig \"LIB_APP_TEST_NAME\")"