required: true
description: "something to summarize or express what this value is and used for"
sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
#suppressWarning: false #whether to suppress warnings for this field or not, defaults to false if not present.
#neverSpawn: false #whether this field should never be spawned or not, defaults to false if not present. Usually used with suppressWarning: true to keep fields from being spawned in the input files.
#indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
#allowed: ".*" #a regex pattern that the value must match, if not present no pattern matching is done.
#default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"