app:
  test:
    manager: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
    name: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
    namespace: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
    version: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
bartholomew:
  jojo:
    simpson: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
psych:
  burton guster: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  chief vic: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  fru it:
    pin-a p_pl e: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  juliet: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  lassie: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  spencer:
    henry: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
    shawn: |-
      required: true
      description: "something to summarize or express what this value is and used for"
      sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
      indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
      #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
ralph:
  wiggum: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
test:
  array: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  corbin: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  hello: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  howdy: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  multipass: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  multipass2: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
  world: |-
    required: true
    description: "something to summarize or express what this value is and used for"
    sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
    indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
    #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
test-howdy: |-
  required: true
  description: "something to summarize or express what this value is and used for"
  sensitive: false #whether the field should be considered sensitive or not, any matching values will be masked in the output.
  indirect: false #whether this field is indirectly referenced or not. If true, will not be deleted on reduce. Not required, if not present assumes false.
  #default: "the default value to use, uncomment and set a value if required is false, delete or leave commented out if required is true"
